<?php

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*****************************************************************************
 * SimpleRisk backup domain.                                                 *
 *                                                                           *
 * Home for database/application backup logic. `generate_database_backup()`  *
 * is a PHP-native (PDO) logical dump that replaces the former mysqldump     *
 * shell-out — no OS command is executed and the DB password never touches a *
 * command line. `do_backup()` is the orchestrator called from both the      *
 * scheduled cron (`cron/cron_backup.php`) and the admin "Backup Now" button *
 * (`admin/settings_backups.php`).                                           *
 *                                                                           *
 * Consumers must `require_once` this file AND `includes/functions.php`      *
 * (this module relies on db_open(), get_setting(), write_debug_log(),       *
 * create_zip_file(), generate_token(), etc. from there).                    *
 *****************************************************************************/

/************************************************************************
 * FUNCTION: GENERATE DATABASE BACKUP                                    *
 * PHP-native (PDO) logical dump of the entire SimpleRisk database to a  *
 * .sql file. Replaces the former mysqldump shell-out — no OS command is *
 * run and the DB password never touches a command line (it travels over *
 * the PDO connection). MySQL only.                                      *
 *                                                                       *
 * The dump is fully dynamic: every BASE TABLE and every column is       *
 * discovered from the live schema at runtime (SHOW FULL TABLES / SHOW   *
 * CREATE TABLE / information_schema), so new tables and columns added by *
 * a migration are backed up automatically with no list to maintain.     *
 * Output shape mirrors `mysqldump --opt` (DROP TABLE IF EXISTS + CREATE  *
 * + batched extended INSERTs, FK checks off) so the existing restore     *
 * path consumes it unchanged.                                           *
 *                                                                       *
 * Returns true on success, false on any failure (and logs the reason).  *
 ************************************************************************/
function generate_database_backup($backup_file)
{
    // Shared connection for schema/metadata reads (SHOW ... / information_schema)
    $db = db_open();
    if (!$db) {
        write_debug_log("Database backup: could not open the database connection.", "error");
        return false;
    }

    // Open the output file
    $fh = @fopen($backup_file, 'w');
    if ($fh === false) {
        write_debug_log("Database backup: could not open '{$backup_file}' for writing.", "error");
        return false;
    }

    // A DEDICATED connection is used to STREAM row data with an unbuffered
    // query, so large tables are read row-by-row instead of loaded whole into
    // memory. It must be separate from db_open()'s shared singleton, because an
    // in-progress unbuffered result blocks any other query on the same handle.
    $stream_db = null;

    try {
        // ---- Header ----
        fwrite($fh, "-- SimpleRisk database backup\n");
        fwrite($fh, "-- Generated by generate_database_backup() (PHP-native; no shell, no external binary)\n");
        fwrite($fh, "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n");
        fwrite($fh, "SET NAMES utf8mb4;\n");
        fwrite($fh, "SET FOREIGN_KEY_CHECKS = 0;\n");
        fwrite($fh, "SET UNIQUE_CHECKS = 0;\n\n");

        // ---- Dedicated unbuffered streaming connection ----
        $stream_options = array(
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false,
            // Return every value as MySQL's own text representation. Without this,
            // mysqlnd hands back FLOAT/DOUBLE as native PHP floats which then
            // stringify at PHP's default precision=14 — silently truncating
            // risk-scoring values (calculated_risk, residual_risk, …). Stringified
            // fetches give the exact server-side text (the same bytes mysqldump
            // emits), so numeric values round-trip byte-identically.
            PDO::ATTR_STRINGIFY_FETCHES => true,
        );
        $stream_db = new PDO(
            "mysql:charset=UTF8;dbname=" . DB_DATABASE . ";host=" . DB_HOSTNAME . ";port=" . DB_PORT,
            DB_USERNAME, DB_PASSWORD, $stream_options
        );
        $stream_db->exec("SET NAMES utf8mb4");
        // Take a consistent point-in-time snapshot of the data for the whole dump
        // (InnoDB), matching mysqldump's --single-transaction consistency without
        // taking a table lock, so a backup captured during live writes is coherent.
        $stream_db->exec("SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ");
        $stream_db->exec("START TRANSACTION WITH CONSISTENT SNAPSHOT");

        // ---- Enumerate base tables from the live schema (dynamic) ----
        $tables = array();
        foreach ($db->query("SHOW FULL TABLES WHERE `Table_type` = 'BASE TABLE'")->fetchAll(PDO::FETCH_NUM) as $row) {
            $tables[] = $row[0];
        }

        // Prepared once and re-executed per table (the SQL text never changes).
        $col_stmt = $db->prepare("
            SELECT `COLUMN_NAME`, `DATA_TYPE`, `EXTRA`
            FROM `information_schema`.`COLUMNS`
            WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = :t
            ORDER BY `ORDINAL_POSITION`
        ");

        foreach ($tables as $table) {
            $qtable = "`" . str_replace('`', '``', $table) . "`";

            // ---- Schema: DROP + CREATE straight from the live definition ----
            fwrite($fh, "DROP TABLE IF EXISTS {$qtable};\n");
            $create = $db->query("SHOW CREATE TABLE {$qtable}")->fetch(PDO::FETCH_NUM);
            fwrite($fh, $create[1] . ";\n\n");

            // ---- Column metadata (dynamic) ----
            // Skip ONLY true generated columns (VIRTUAL/STORED GENERATED) — they
            // cannot be inserted into. DEFAULT_GENERATED columns (DEFAULT
            // CURRENT_TIMESTAMP / ON UPDATE CURRENT_TIMESTAMP) are ordinary data
            // columns and MUST be dumped with their stored values.
            $col_stmt->execute(array(':t' => $table));

            $columns = array();      // ordered column names to dump
            $is_binary = array();    // column name => needs 0x-hex encoding
            foreach ($col_stmt->fetchAll(PDO::FETCH_ASSOC) as $col) {
                $extra = strtoupper((string)$col['EXTRA']);
                if (strpos($extra, 'VIRTUAL GENERATED') !== false || strpos($extra, 'STORED GENERATED') !== false) {
                    continue;
                }
                $name = $col['COLUMN_NAME'];
                $columns[] = $name;
                $is_binary[$name] = in_array(strtolower((string)$col['DATA_TYPE']), array(
                    'blob', 'tinyblob', 'mediumblob', 'longblob', 'binary', 'varbinary', 'bit'
                ), true);
            }
            if (!$columns) {
                fwrite($fh, "\n");
                continue;
            }

            $col_list = implode(', ', array_map(function ($c) {
                return "`" . str_replace('`', '``', $c) . "`";
            }, $columns));
            $insert_prefix = "INSERT INTO {$qtable} ({$col_list}) VALUES\n";

            // ---- Data: stream rows, emit batched extended INSERTs ----
            $data = $stream_db->query("SELECT {$col_list} FROM {$qtable}");
            $rows_in_batch = 0;
            $bytes_in_batch = 0;
            $open_statement = false;

            while ($row = $data->fetch(PDO::FETCH_NUM)) {
                $vals = array();
                foreach ($columns as $i => $name) {
                    $v = $row[$i];
                    if ($v === null) {
                        $vals[] = 'NULL';
                    } elseif ($is_binary[$name]) {
                        // 0x needs at least one hex digit; an empty binary is ''
                        $vals[] = ($v === '') ? "''" : '0x' . bin2hex($v);
                    } else {
                        $vals[] = $db->quote($v);
                    }
                }
                $row_sql = '(' . implode(',', $vals) . ')';

                if (!$open_statement) {
                    fwrite($fh, $insert_prefix . $row_sql);
                    $open_statement = true;
                } else {
                    fwrite($fh, ",\n" . $row_sql);
                }
                $rows_in_batch++;
                $bytes_in_batch += strlen($row_sql);

                // Bound the size of any single extended-INSERT statement
                if ($rows_in_batch >= 1000 || $bytes_in_batch >= 4194304) {
                    fwrite($fh, ";\n");
                    $open_statement = false;
                    $rows_in_batch = 0;
                    $bytes_in_batch = 0;
                }
            }
            if ($open_statement) {
                fwrite($fh, ";\n");
            }
            $data->closeCursor();
            fwrite($fh, "\n");
        }

        // ---- Footer ----
        fwrite($fh, "SET FOREIGN_KEY_CHECKS = 1;\n");
        fwrite($fh, "SET UNIQUE_CHECKS = 1;\n");

        fclose($fh);
        $stream_db = null;
        return true;
    } catch (\Throwable $e) {
        write_debug_log("Database backup failed: " . $e->getMessage(), "error");
        if (is_resource($fh)) {
            fclose($fh);
        }
        // Remove the partial/truncated dump so it can't be mistaken for a valid
        // backup by an operator or a retention/cleanup script.
        if (file_exists($backup_file)) {
            @unlink($backup_file);
        }
        $stream_db = null;
        return false;
    }
}

/*****************************************************************************
 * FUNCTION: DO BACKUP                                                        *
 * Orchestrates a full backup: a database dump (via generate_database_backup) *
 * zipped, an application-files zip, a `backups` row, and retention cleanup.  *
 * $requested_from_ui=true routes user-facing messages through set_alert()    *
 * (there is a session); the cron path logs instead. Called from              *
 * cron/cron_backup.php (scheduled) and admin/settings_backups.php ("Backup   *
 * Now").                                                                      *
 *****************************************************************************/
function do_backup($requested_from_ui = false) {
    // Create a timestamp for the current date and time
    $timestamp = date("Y-m-d--H-i-s");

    // Get the backup directory path
    $backup_path = get_setting('backup_path');

    // Set the error to false
    $error = false;

    // If the backup directory does not exist
    if (!is_dir($backup_path))
    {
        // If we could not create the backup directory
        if (!mkdir($backup_path))
        {
            // We have a problem
            $error = true;

            // Write a message to the error log
            $message = "Unable to create a backup directory under " . $backup_path . ".";

            // If the backup was requested from the UI
            if ($requested_from_ui) {
                set_alert(true, "bad", $message);
            } else {
                write_debug_log($message, "error");
            }
        }
    }

    // Get the path to the timestamp directory for this backup
    $timestamp_path = $backup_path . '/' . $timestamp;

    // If the timestamp directory does not exist
    if (!$error && !is_dir($timestamp_path))
    {
        // If we could not create the timestamp directory
        if (!mkdir($timestamp_path))
        {
            // We have a problem
            $error = true;

            // Write a message to the error log
            $message = "Unable to create a backup directory under " . $timestamp_path . ".";

            // If the backup was requested from the UI
            if ($requested_from_ui) {
                set_alert(true, "bad", $message);
            } else {
                write_debug_log($message, "error");
            }
        }
    }

    if ($error) {
        $message = "Backup failed.";
        write_log(0, 0, $message, 'backup');

        // If the backup was requested from the UI
        if ($requested_from_ui) {
            set_alert(true, "bad", $message);
        } else {
            write_debug_log($message, "error");
        }

        return;
    }

    // Get the path to the database backup file
    $db_backup_file = $timestamp_path . '/simplerisk-db-backup-' . $timestamp . '.sql';

    // Generate the database backup (PHP-native; no shell, no mysqldump binary).
    // Abort the whole backup if the dump fails rather than zipping a partial/empty file.
    // $db_backup_file is composed from the admin-only `backup_path` setting plus a
    // server-generated timestamp and a fixed filename — no user-controlled path
    // component, and an admin who can set backup_path already controls the app.
    // @phan-suppress-next-line SecurityCheck-PathTraversal
    if (!generate_database_backup($db_backup_file)) {
        $message = "Database backup failed.";
        write_log(0, 0, $message, 'backup');

        if ($requested_from_ui) {
            set_alert(true, "bad", $message);
        } else {
            write_debug_log($message, "error");
        }

        return;
    }

    $db_zip_file_name = $timestamp_path . '/simplerisk-db-backup-' . $timestamp . '.zip';
    create_zip_file($db_backup_file, $db_zip_file_name);

    // Remove the uncompressed database backup
    unlink($db_backup_file);

    // Create a zip file containing the current SimpleRisk files
    $simplerisk_directory =  realpath(__DIR__) . '/../';
    $app_zip_file_name = $timestamp_path . '/simplerisk-app-backup-' . $timestamp . '.zip';
    create_zip_file($simplerisk_directory, $app_zip_file_name);

    // Get the number of days to keep backups for
    $backup_remove = (int)get_setting('backup_remove');

    // Create a random id for the backup
    $random_id = generate_token(50);

    // Open the database connection
    $db = db_open();

    // Insert the backup information into the database
    $stmt = $db->prepare("INSERT INTO `backups` (`random_id`, `timestamp`, `app_zip_file_name`, `db_zip_file_name`) VALUES (:random_id, :timestamp, :app_zip_file_name, :db_zip_file_name);");
    $stmt->bindParam(":random_id", $random_id, PDO::PARAM_STR, 50);
    $stmt->bindParam(":timestamp", $timestamp, PDO::PARAM_STR);
    $stmt->bindParam(":app_zip_file_name", $app_zip_file_name, PDO::PARAM_STR);
    $stmt->bindParam(":db_zip_file_name", $db_zip_file_name, PDO::PARAM_STR);
    $stmt->execute();

    // Get the list of expired backups
    $stmt = $db->prepare("SELECT * FROM `backups` WHERE timestamp < (NOW() - INTERVAL :backup_remove DAY);");
    $stmt->bindParam(":backup_remove", $backup_remove, PDO::PARAM_INT);
    $stmt->execute();
    $backups_to_delete = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (!empty($backups_to_delete)) {

        $message = "Removing backup(s) older than {$backup_remove} day(s).";
        write_log(0, 0, $message, 'backup');

        // If the backup was requested from the UI
        if ($requested_from_ui) {
            set_alert(true, "good", $message);
        } else {
            write_debug_log($message, "info");
        }

        // Iterate through the list of expired backups and clean them up
        foreach ($backups_to_delete as $backup_to_delete) {
            delete_backup($backup_to_delete, $requested_from_ui);
        }
    }
    $message = "Backup successfully completed.";
    write_log(0, 0, $message, 'backup');

    // If the backup was requested from the UI
    if ($requested_from_ui) {
        set_alert(true, "good", $message);
    } else {
        write_debug_log($message, "notice");
    }
}
