<?php
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// SimpleRisk runtime bootstrap. Every entry point that needs a working
// configuration includes this file (directly or transitively) instead of
// require_once'ing config.php straight. The presence of config.php and a
// complete set of required DB_* defines is the install marker — a missing
// or partial config routes HTTP requests to the installer and aborts CLI
// scripts with a clear error, rather than fataling deep inside db_open()
// on an undefined constant.
//
// Idempotent: subsequent require_once's are no-ops, and a second call
// still observes the now-defined constants and returns immediately.

require_once(__DIR__ . '/config_check.php');

$config_file_path = __DIR__ . '/config.php';
if (file_exists($config_file_path)) {
    // @phan-suppress-next-line PhanMissingRequireFile -- config.php is generated by the installer at runtime; intentionally not committed (see config.sample.php and .gitignore)
    require_once($config_file_path);
    if (config_defines_all_present(config_required_db_defines())) {
        return;
    }
}

// Config missing or incomplete — dispatch by SAPI.
if (PHP_SAPI === 'cli') {
    fwrite(STDERR,
        "SimpleRisk is not yet installed (config file missing or incomplete at " .
        $config_file_path . "). Browse to the application root in a web browser " .
        "to run the installer, then re-run this script.\n"
    );
    exit(1);
}

// HTTP context — render the installer page in place of whatever the caller
// would have produced. install.php deliberately does not require config.php,
// so it is safe to load here.
require_once(realpath(__DIR__ . '/install.php'));
simplerisk_installation();
exit;
